# Generated by Django 3.2.6 on 2021-08-30 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210831_0032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
